In [2]:
import seaborn as sns

In [3]:
iris = sns.load_dataset('iris')

In [13]:
iris.describe(include='all')

sepal_length  sepal_width  petal_length  petal_width species
count     150.000000   150.000000    150.000000   150.000000     150
unique           NaN          NaN           NaN          NaN       3
top              NaN          NaN           NaN          NaN  setosa
freq             NaN          NaN           NaN          NaN      50
mean        5.843333     3.057333      3.758000     1.199333     NaN
std         0.828066     0.435866      1.765298     0.762238     NaN
min         4.300000     2.000000      1.000000     0.100000     NaN
25%         5.100000     2.800000      1.600000     0.300000     NaN
50%         5.800000     3.000000      4.350000     1.300000     NaN
75%         6.400000     3.300000      5.100000     1.800000     NaN
max         7.900000     4.400000      6.900000     2.500000     NaN

In [14]:
import numpy as np
iris_array = iris.iloc[:,:-1].to_numpy()

In [15]:
type(iris_array)

numpy.ndarray

In [16]:
iris_array.shape

(150, 4)

In [17]:
from scipy.stats import kurtosis, skew

In [18]:
# normal : 정규분포(가우시안), uniform : 균등분포
data = np.random.normal(0,1,10000000)

In [19]:
np.mean(data), np.var(data), np.std(data), skew(data), kurtosis(data)

(0.00026834230560537155,
 0.9999424549103454,
 0.9999712270412311,
 -0.0002457780831143644,
 0.0018753208368758045)

In [31]:
from dataprep.eda import plot, plot_correlation, plot_missing

### iris.species[0:100] 를 레이블 인코딩 하세요.

In [4]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [8]:
le.fit(iris.species)

LabelEncoder()

In [9]:
le.transform(iris.species[0:100])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [10]:
le.classes_

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [11]:
data = [0,1,1,1,0,0,2,1,2,1,2] #이 값의 종 이름을 출력하세요

In [13]:
le.inverse_transform(data)

array(['setosa', 'versicolor', 'versicolor', 'versicolor', 'setosa',
       'setosa', 'virginica', 'versicolor', 'virginica', 'versicolor',
       'virginica'], dtype=object)

In [14]:
le.classes_[data]

array(['setosa', 'versicolor', 'versicolor', 'versicolor', 'setosa',
       'setosa', 'virginica', 'versicolor', 'virginica', 'versicolor',
       'virginica'], dtype=object)

In [34]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()

In [36]:
enc.fit(iris.species.to_numpy().reshape(-1,1))

OneHotEncoder()

In [38]:
iris_onehot=enc.transform(iris.species.to_numpy().reshape(-1,1))

In [39]:
iris_onehot.toarray()

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [40]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
lb.fit(iris.species)
lb.transform(iris.species)

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [41]:
import pandas as pd
pd.get_dummies(iris.species)

setosa  versicolor  virginica
0         1           0          0
1         1           0          0
2         1           0          0
3         1           0          0
4         1           0          0
..      ...         ...        ...
145       0           0          1
146       0           0          1
147       0           0          1
148       0           0          1
149       0           0          1

[150 rows x 3 columns]

In [45]:
from sklearn.model_selection import train_test_split
X = iris.iloc[:,:-1]
y = iris.species
train_X,test_X,train_y,test_y = train_test_split(X, y,test_size=0.3,stratify =y)

In [46]:
train_X.shape, test_X.shape, train_y.shape, test_y.shape

((105, 4), (45, 4), (105,), (45,))

In [47]:
train_y.value_counts()

versicolor    35
virginica     35
setosa        35
Name: species, dtype: int64

In [76]:
iris = sns.load_dataset('iris')

In [77]:
iris_mean_by_species = iris.groupby('species').mean()
iris_mean_by_species

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa             5.006        3.428         1.462        0.246
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [81]:
import seaborn as sns
iris = sns.load_dataset('iris')
iris_X = iris.iloc[:,:-1]
iris_y = iris.iloc[:,-1]

In [82]:
import random
random.seed(7902)
for col in range(4):
    iris_X.iloc[[random.sample(range(len(iris)),20)],col]=float('nan')

In [83]:
iris_n = pd.concat([iris_X,iris_y], axis=1)

In [88]:
import math
def na2mean(row):
    for i in range(4):
        if(math.isnan(row[i])):
            row[i] = iris_mean_by_species.loc[row['species'], row.index[i]]
    return row

In [87]:
iris_X

sepal_length  sepal_width  petal_length  petal_width
0             NaN          3.5           NaN          0.2
1             4.9          NaN           1.4          0.2
2             4.7          3.2           NaN          NaN
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           NaN          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [89]:
iris_new = iris_n.apply(na2mean,axis=1)
iris_new.head()

sepal_length       NaN
sepal_width        3.5
petal_length       NaN
petal_width        0.2
species         setosa
Name: 0, dtype: object
sepal_length     5.006
sepal_width        3.5
petal_length       NaN
petal_width        0.2
species         setosa
Name: 0, dtype: object
sepal_length     5.006
sepal_width        3.5
petal_length       NaN
petal_width        0.2
species         setosa
Name: 0, dtype: object
sepal_length     5.006
sepal_width        3.5
petal_length     1.462
petal_width        0.2
species         setosa
Name: 0, dtype: object
sepal_length       4.9
sepal_width        NaN
petal_length       1.4
petal_width        0.2
species         setosa
Name: 1, dtype: object
sepal_length       4.9
sepal_width        NaN
petal_length       1.4
petal_width        0.2
species         setosa
Name: 1, dtype: object
sepal_length       4.9
sepal_width      3.428
petal_length       1.4
petal_width        0.2
species         setosa
Name: 1, dtype: object
sepal_length       4.9
sepal_width

Name: 97, dtype: object
sepal_length           6.2
sepal_width            2.9
petal_length           4.3
petal_width            NaN
species         versicolor
Name: 97, dtype: object
sepal_length           6.2
sepal_width            2.9
petal_length           4.3
petal_width            NaN
species         versicolor
Name: 97, dtype: object
sepal_length           5.1
sepal_width            2.5
petal_length           3.0
petal_width            1.1
species         versicolor
Name: 98, dtype: object
sepal_length           5.1
sepal_width            2.5
petal_length           3.0
petal_width            1.1
species         versicolor
Name: 98, dtype: object
sepal_length           5.1
sepal_width            2.5
petal_length           3.0
petal_width            1.1
species         versicolor
Name: 98, dtype: object
sepal_length           5.1
sepal_width            2.5
petal_length           3.0
petal_width            1.1
species         versicolor
Name: 98, dtype: object
sepal_length          

sepal_length  sepal_width  petal_length  petal_width species
0         5.006        3.500         1.462        0.200  setosa
1         4.900        3.428         1.400        0.200  setosa
2         4.700        3.200         1.462        0.246  setosa
3         4.600        3.100         1.500        0.200  setosa
4         5.000        3.600         1.400        0.200  setosa

In [86]:
iris

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]