### 넘파이 배열

In [1]:
# arange로 배열 생성 후 reshape으로 변환
import numpy as np
A= np.arange(15).reshape(3,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
type(A)

numpy.ndarray

In [3]:
A.shape

(3, 5)

In [4]:
#축의 개수를 반환한다
A.ndim

2

In [5]:
# dtype name을 통해서 요소의 유형을 알 수 있다.
A.dtype.name

'int32'

In [6]:
A.itemsize #(4byte)

4

In [7]:
#요소 전체의 개수를 알 수 있다.
A.size

15

In [10]:
my_a=np.array([1_0000_0000_0000,2,3])

In [16]:
print(my_a.ndim)
print(my_a.shape)
print(my_a.size)
print(my_a.dtype)
print(my_a[0].itemsize)
print(my_a[1].itemsize)

1
(3,)
3
int64
8
8


In [18]:
A=np.arange(12,dtype=np.int32).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
#dtype 속성을 이용해서 형 변환을 해서는 안된다.
A.dtype=np.int64
A

array([[ 4294967296, 12884901890],
       [21474836484, 30064771078],
       [38654705672, 47244640266]], dtype=int64)

In [21]:
#넘파이 배열
A=np.array([2,3,4])
A.dtype

dtype('int32')

In [22]:
B=np.array([1.2,3.5,5.1])
B.dtype

dtype('float64')

In [23]:
#단일 숫자 목록을 인수로 하지 않고 여러개로 인수를 줄 경우
A=np.array(1,2,3,4)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [24]:
A=np.array([1,2,3,4,5]) #단일 인수로 array 생성해야 한다.

In [25]:
#array함수는 1차원을 2차원으로 2차원을 3차원 배열로 변환할 때 수행한다.
B=np.array([[1.5,2.,3.], [4.,5.,6.]])
B

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [27]:
C=np.array([[1,2],[3,4]], dtype=complex)
C

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [28]:
C= np.array([[1,2],[3,4]],dtype=np.float32)
C

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [30]:
# copy=False 이면 새로운 배열의 복사본이 생성되지 않는다
D=np.array(C,copy=False)
print(id(C),id(D))

2707362506384 2707362506384


In [31]:
# copy=False 여도 type이 새로운 걸 지정하면 복사본 생성
D=np.array(C,copy=False,dtype=int)
print(id(C),id(D)) #C는 기존에 float type이였다.

2707362506384 2707362376656


In [32]:
#기본값이 있는 배열 만들기
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
x=np.zeros((3,4))
x.dtype

dtype('float64')

In [34]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [35]:
# empty는 garbage collection에 있는 쓰레기 데이터를 기초로 생성
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [38]:
#연속된 값을 갖는 배열 만들기
#arange() 함수는 range() 함수와 비슷하다
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(11,20)

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [40]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [41]:
# arange float또한 가능하다
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [42]:
#linspace() 이용하기
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [43]:
# 0~10까지 20개의 숫자로 나눌 때 값이 0.5가 아닌걸 주의
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [46]:
x= np.linspace(0,2*np.pi,100)
y=np.sin(x)
print(y)

[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.42020143e-01
 -4.00930535e-01 -4.58226522e-01 -5.13677392e-01 -5.67059864e-01
 -6.18158986e-01 -6.66769

In [47]:
#배열 모양 변경하기
A=np.arange(12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
A.shape

(3, 4)

In [49]:
#차원이 풀린 배열을 반환한다.
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [50]:
#shape가 수정된 배열을 반환
A.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [51]:
# 전치행렬을 반환한다.
A.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [52]:
A=np.arange(12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
# resize는 원본 배열 자체를 수정
A.resize(2,6)
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [62]:
# reshape은 반환만 해준다
A.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [55]:
A.resize(2,-1)

ValueError: negative dimensions not allowed

In [64]:
# shape를 직접 지정해서도 수정할 수 있다.
print(A)
A.shape=(12,)
print(A)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [66]:
A=np.arange(6)
print(A)

[0 1 2 3 4 5]


In [67]:
B=np.arange(12).reshape(4,3)
print(B)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [68]:
C=np.arange(24).reshape(2,3,4)
print(C)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [69]:
#배열의 중앙부분은 길어서 생략되서 출력된다
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [ ]:
#을 사용하면 전체 출력을 할 수 있다 threshold값을 통해서
numpy.set_printoptions(threshold=None)