##### 인덱싱,슬라이싱

In [2]:
import numpy as np
A=np.arange(10)**3
A

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [3]:
A[2]

8

In [4]:
A[2:5]

array([ 8, 27, 64], dtype=int32)

In [5]:
A[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0], dtype=int32)

In [7]:
A[::2]=-1
A

array([ -1,   1,  -1,  27,  -1, 125,  -1, 343,  -1, 729], dtype=int32)

In [11]:
# 2차원 배열
B=np.arange(20).reshape(5,4)
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [12]:
B[2,3]

11

In [14]:
# 3차원 배열
C=np.arange(24).reshape(2,3,4)
C

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [15]:
C[0,1,2]

6

In [16]:
C[1,2,3]

23

In [23]:
#다차원 배열 슬라이싱
print(B)
B[0:5,1]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


array([ 1,  5,  9, 13, 17])

In [21]:
B[:,1]

array([ 1,  5,  9, 13, 17])

In [22]:
B[1:3,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
#2차원 배열은 열 인덱스는 생략가능 행 인덱스 생략 불가
B[,:]

SyntaxError: invalid syntax (<ipython-input-25-de1a9179a294>, line 2)

In [28]:
print(B)
B[-1] #B[-1,:]와 동일하다

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


array([16, 17, 18, 19])

In [29]:
print(C)
C[0]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
C[:,:,0]

array([[ 0,  4,  8],
       [12, 16, 20]])

In [31]:
C[...,0]

array([[ 0,  4,  8],
       [12, 16, 20]])

In [33]:
C[:,0,]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])