##### 인덱싱,슬라이싱

In [2]:
import numpy as np
A=np.arange(10)**3
A

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [3]:
A[2]

8

In [4]:
A[2:5]

array([ 8, 27, 64], dtype=int32)

In [5]:
A[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0], dtype=int32)

In [7]:
A[::2]=-1
A

array([ -1,   1,  -1,  27,  -1, 125,  -1, 343,  -1, 729], dtype=int32)

In [11]:
# 2차원 배열
B=np.arange(20).reshape(5,4)
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [12]:
B[2,3]

11

In [14]:
# 3차원 배열
C=np.arange(24).reshape(2,3,4)
C

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [15]:
C[0,1,2]

6

In [16]:
C[1,2,3]

23

In [23]:
#다차원 배열 슬라이싱
print(B)
B[0:5,1]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


array([ 1,  5,  9, 13, 17])

In [21]:
B[:,1]

array([ 1,  5,  9, 13, 17])

In [22]:
B[1:3,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
#2차원 배열은 열 인덱스는 생략가능 행 인덱스 생략 불가
B[,:]

SyntaxError: invalid syntax (<ipython-input-25-de1a9179a294>, line 2)

In [28]:
print(B)
B[-1] #B[-1,:]와 동일하다

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


array([16, 17, 18, 19])

In [29]:
print(C)
C[0]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
C[:,:,0]

array([[ 0,  4,  8],
       [12, 16, 20]])

In [31]:
C[...,0]

array([[ 0,  4,  8],
       [12, 16, 20]])

In [33]:
C[:,0,]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [4]:
import numpy as np
B=np.arange(20).reshape(5,4)
#첫번째 축기준으로 수행
for row in B:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]


In [7]:
C=np.arange(24).reshape(2,3,4)
for i,data in enumerate(C):
    for j,row in enumerate(data):
        for k,cell in enumerate(row):
            print("[{},{},{}-{}]".format(i,j,k,cell),end=', ')

[0,0,0-0], [0,0,1-1], [0,0,2-2], [0,0,3-3], [0,1,0-4], [0,1,1-5], [0,1,2-6], [0,1,3-7], [0,2,0-8], [0,2,1-9], [0,2,2-10], [0,2,3-11], [1,0,0-12], [1,0,1-13], [1,0,2-14], [1,0,3-15], [1,1,0-16], [1,1,1-17], [1,1,2-18], [1,1,3-19], [1,2,0-20], [1,2,1-21], [1,2,2-22], [1,2,3-23], 

In [10]:
for element in B.flat:
    print(element,end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 

In [18]:
A=np.arange(12).reshape(3,4)
B=np.arange(12,24).reshape(3,4)
print(A)
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [13]:
np.vstack((A,B))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
np.hstack((A,B))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [15]:
np.dstack((A,B))

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [16]:
np.column_stack((A,B))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [23]:
# column_stack 함수는 1차원 배열을 열 단위로 합쳐 2차원으로 2차원은 2차원으로
A=np.array((1,2,3,4))
B=np.array((5,6,7,8))
C=np.array((9,10,11,12))
np.column_stack((A,B,C))

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [24]:
print(A)
print(B)
#1차원 배열을 쌓으면 1차원 배열이 나온다
np.hstack((A,B))

[1 2 3 4]
[5 6 7 8]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
#1차원 배열을 쌓으면 2차원 배열이 나온다
np.column_stack((A,B))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [27]:
A=np.array((1,2,3,4))
B=np.array((5,6,7,8))

In [28]:
A[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4]])

In [29]:
np.column_stack((A,B))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [31]:
np.column_stack((A,B))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [34]:
print(np.hstack((A[:,np.newaxis],B[:,np.newaxis])))
print(np.hstack((A,B)))

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[1 2 3 4 5 6 7 8]


In [37]:
print(A,B)
print(np.vstack((A[:,np.newaxis],B[:,np.newaxis])))
print(np.vstack((A,B)))

[1 2 3 4] [5 6 7 8]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2 3 4]
 [5 6 7 8]]


In [42]:
A=np.arange(12).reshape(3,4)
B=np.arange(12,24).reshape(3,4)
print(A,B,sep='\n')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [40]:
np.stack((A,B),axis=0)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [43]:
A=np.array((1,2,3,4))
B=np.array((5,6,7,8))
C=np.array((9,10,11,12))
# 행 단위로 한개의 축을 따라 데이터를 나열해서 배열
np.r_[A,B,C]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [44]:
# 행 단위로 차원을 추가 할 수도 있다
np.r_[[A],[B],[C]]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
# 열 단위로 한개의 축을 따라 데이터를 나열해서 배열
np.c_[A,B,C]

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [48]:
np.c_[C,B,A]

array([[ 9,  5,  1],
       [10,  6,  2],
       [11,  7,  3],
       [12,  8,  4]])

In [50]:
A=np.arange(12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
A_vsplit=np.vsplit(A,3)
A_vsplit

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [54]:
A_hsplit=np.hsplit(A,4) 
A_hsplit

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [55]:
C=np.arange(24).reshape(2,3,4)
C

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [58]:
C_hsplit=np.hsplit(C,3)
C_hsplit

[array([[[ 0,  1,  2,  3]],
 
        [[12, 13, 14, 15]]]),
 array([[[ 4,  5,  6,  7]],
 
        [[16, 17, 18, 19]]]),
 array([[[ 8,  9, 10, 11]],
 
        [[20, 21, 22, 23]]])]

In [59]:
np.dsplit(C,2)

[array([[[ 0,  1],
         [ 4,  5],
         [ 8,  9]],
 
        [[12, 13],
         [16, 17],
         [20, 21]]]),
 array([[[ 2,  3],
         [ 6,  7],
         [10, 11]],
 
        [[14, 15],
         [18, 19],
         [22, 23]]])]

In [61]:
A=np.arange(24).reshape(3,8)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [63]:
A_split=np.hsplit(A,(2,5,6))
A_split

[array([[ 0,  1],
        [ 8,  9],
        [16, 17]]),
 array([[ 2,  3,  4],
        [10, 11, 12],
        [18, 19, 20]]),
 array([[ 5],
        [13],
        [21]]),
 array([[ 6,  7],
        [14, 15],
        [22, 23]])]

In [64]:
B=np.arange(24).reshape(3,8)
B

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [65]:
np.split(B,3,axis=0)

[array([[0, 1, 2, 3, 4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20, 21, 22, 23]])]

In [66]:
np.hsplit(B,2)

[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23]])]

In [67]:
np.split(B,2,axis=1)

[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23]])]

In [71]:
A=np.arange(20).reshape(2,10)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [72]:
# 10을 3으로 나눌 수 없다
np.split(A,3,axis=1)

ValueError: array split does not result in an equal division

In [73]:
np.array_split(A,3,axis=1)

[array([[ 0,  1,  2,  3],
        [10, 11, 12, 13]]),
 array([[ 4,  5,  6],
        [14, 15, 16]]),
 array([[ 7,  8,  9],
        [17, 18, 19]])]

In [74]:
np.array_split(A,4,axis=1)

[array([[ 0,  1,  2],
        [10, 11, 12]]),
 array([[ 3,  4,  5],
        [13, 14, 15]]),
 array([[ 6,  7],
        [16, 17]]),
 array([[ 8,  9],
        [18, 19]])]