### 배열의 요소별 연산

In [2]:
import numpy as np
A=np.array([20,30,40,50])
B=np.arange(4)

In [3]:
A-B

array([20, 29, 38, 47])

In [4]:
B**2

array([0, 1, 4, 9], dtype=int32)

In [5]:
10*np.sin(A)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [7]:
A>35

array([False, False,  True,  True])

In [10]:
#행렬의 곱
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])

In [11]:
#요소별 곱셈
A*B

array([[2, 0],
       [0, 4]])

In [13]:
#행렬의 곱셈
A.dot(B)
A @ B

array([[5, 4],
       [3, 4]])

In [14]:
#복합대입연산자의 사용
A=np.ones((2,3), dtype=np.int32)
B=np.arange(6).reshape(2,3).astype(np.float32)

In [16]:
A*=3
A

array([[9, 9, 9],
       [9, 9, 9]])

In [17]:
B+=A
B

array([[ 9., 10., 11.],
       [12., 13., 14.]], dtype=float32)

In [20]:
A=np.ones(3, dtype=np.int32)
B=np.linspace(0, np.pi,3)
print(A.dtype.name,B.dtype.name)

int32 float64


In [22]:
# int 와 float의 결합은 float유형으로
C=A+B
print(C.dtype.name)

float64


In [23]:
A=np.arange(12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
#배열 요소의 집계
A.sum(),A.min(),A.max(),A.mean(),A.std()

(66, 0, 11, 5.5, 3.452052529534663)

In [26]:
#축을 기준으로 요소의 집계
A=np.arange(12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
A.sum(axis=0)

array([12, 15, 18, 21])

In [28]:
A.sum(axis=1)

array([ 6, 22, 38])

In [29]:
B=np.arange(24).reshape(2,3,4)
B

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [30]:
B.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [31]:
B.sum(axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [32]:
B.sum(axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [34]:
#형변환을 해줄 수도 있다.
y=np.int_([1,2.3,4])
y.dtype
print(y)

[1 2 4]


In [35]:
#범용 함수의 사용
A=np.arange(3)
B=np.arange(4,7)
A+B

array([4, 6, 8])

In [36]:
np.add(A,B)

array([4, 6, 8])

In [37]:
id(A),id(B)

(1666402336560, 1666402566576)

In [38]:
# 출력 인수를 사용해 더한 값을 바로 A에 저장해서 사용할 수 있다.
np.add(A,B,A)

array([4, 6, 8])

In [39]:
id(A)

1666402336560

In [41]:
#출력 인수의 사용과 메모리 사용량 및 실행시간 비교
!pip install memory_profiler

  Created wheel for memory-profiler: filename=memory_profiler-0.58.0-py3-none-any.whl size=30183 sha256=c892c7ed30648db11062fb825b1ec3774a7fe7df9805c782fb145f90b78879fd
  Stored in directory: c:\users\san\appdata\local\pip\cache\wheels\6a\37\3e\d9e8ebaf73956a3ebd2ee41869444dbd2a702d7142bcf93c42
Successfully built memory-profiler


In [42]:
%load_ext memory_profiler

In [43]:
A=np.random.randn(100000000)
B=np.random.randn(100000000)
C=np.random.randn(100000000)

In [44]:
%%time
%memit G = A*B+C
print(G)

peak memory: 3389.62 MiB, increment: 1049.38 MiB
[-0.73308945 -0.54928782  0.7112204  ...  1.18217905 -1.82652579
 -1.62966792]
Wall time: 5.68 s


In [45]:
%%time
%memit T1=A*B; G=T1+C; del T1
print(G)

peak memory: 3236.00 MiB, increment: 1669.62 MiB
[-0.73308945 -0.54928782  0.7112204  ...  1.18217905 -1.82652579
 -1.62966792]
Wall time: 16.1 s


In [46]:
%%time
%memit G=A*B; G += C
print(G)

peak memory: 2628.32 MiB, increment: 2281.31 MiB
[-0.73308945 -0.54928782  0.7112204  ...  1.18217905 -1.82652579
 -1.62966792]
Wall time: 10.6 s


In [47]:
%%time
%memit G=A*B; np.add(G,C,G)
print(G)

peak memory: 3815.49 MiB, increment: 1192.64 MiB
[-0.73308945 -0.54928782  0.7112204  ...  1.18217905 -1.82652579
 -1.62966792]
Wall time: 2.26 s


In [48]:
#브로드캐스팅 규칙
#연산의 두 배열에 대한 후미 축의 크기가 같거나 둘 중 하나가 1이어야 한다.
A=np.array([[0,0,0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
B=np.array([1,2,3])

In [49]:
#(4,3) (1,3) 의 연산
A+B

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [52]:
A=np.array([0,10,20,30])
B=np.array([1.0,2.0,3.0])
A[:,np.newaxis]+B #A[:,np.newaxis]는 4x1모양의 2차원 배열

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])